# Use Node.js image
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the source code and the .env file
COPY ./src /app/src
COPY .env /app/.env

# Expose the application's port
EXPOSE 8080

# Start the Node.js server, pointing to the correct file (src/index.js)
CMD ["node", "src/index.js"]
