version: "3.8"

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:8080"
        volumes:
            - uploads-data:/app/uploads

volumes:
    uploads-data:
